config_version = 12

[backdrop]
enabled = true

[bar]
order = [ "default" ]

    [bar.default]
    background_opacity = 0.89999997988343239
    border = "primary"
    capsule_thickness = 0.10000000149011612
    color = "primary"
    end = [ "bluetooth", "volume", "keyboard_layout", "notifications", "tray" ]
    font_weight = 600
    margin_edge = 8
    margin_ends = 8
    panel_overlap = 0
    radius = 20
    scale = 1.1500000096857548
    start = [ "workspaces" ]
    thickness = 32

        [bar.default.dead_zone.actions]
        right = "none"

[control_center]
hidden_tabs = [ "monitor", "power", "bluetooth", "weather" ]
show_shortcut_labels = false
sidebar_section = "none"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "clipboard"

    [[control_center.shortcuts]]
    type = "audio"

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
background_opacity = 0.90999997965991497

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 300.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 600.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = false
    timeout = 600.0

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@DVI-D-1", "lockscreen-widget-0000000000000006", "lockscreen-widget-0000000000000007" ]

    [lockscreen_widgets.grid]
    cell_size = 8
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DVI-D-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 640.0
    cy = 864.0
    output = "DVI-D-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DVI-D-1".settings]
        background_color = "surface"
        background_opacity = 0.90000000000000002
        background_radius = 20.0
        center_password_text = true
        input_opacity = 0.90000000000000002
        input_radius = 20.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = false
        show_weather = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000006]
    box_height = 200.0
    box_width = 376.0
    cx = 632.0
    cy = 524.0
    output = "DVI-D-1"
    rotation = -0.0
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000006.settings]
        background = false
        background_opacity = 0.90000000000000002
        background_radius = 20
        bands = 32
        centered = false
        mirrored = true
        show_when_idle = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000007]
    box_height = 144.0
    box_width = 384.0
    cx = 632.0
    cy = 694.0
    output = "DVI-D-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000007.settings]
        background_opacity = 0.90000000000000002
        background_radius = 20
        color = "primary"
        shadow = false

[notification]
background_opacity = 0.89999997988343239
layer = "overlay"
show_actions = false

[osd]
background_opacity = 0.89999997988343239
offset_y = 14
position = "bottom_center"
position_vertical = "bottom_center"

    [osd.kinds]
    bluetooth = false
    brightness = false
    keyboard_backlight = false
    keyboard_layout = false
    lock_keys = false
    media = false
    nightlight = false
    power_profile = false
    privacy = false
    wifi = false

[plugin_settings."noctalia/screen_recorder"]
filename_pattern = "record-%H:%M_%d.%m"
replay_duration = 15
replay_enabled = true
replay_filename_pattern = "replay-%H:%M_%d.%m"
show_cursor = false
video_source = "focused"

[plugin_settings."noctalia/timer"]
panel_open_near_click = false
panel_placement = "floating"

[plugin_settings."nomadcxx/gslapper"]
glyph = ""
picker_placement = "floating"
scale = "stretch"

[plugin_settings."radimous/prismlauncher-instances"]
launcher_exec_command = "elyprismlauncher"
prism_path = "~/.local/share/ElyPrismLauncher"

[plugin_settings."yocraft/web-launcher"]
icon_provider = "duckduckgo"
links = [
    "Soundcloud|https://soundcloud.com/",
    "YouTube|https://youtube.com",
    "Reddit|https://reddit.com",
    "Mail|https://mail.proton.me",
    "GitHub|https://github.com"
]

[plugin_settings."yuuto/arch-updater"]
aur_helper = "paru"
flatpak_enabled = false
panel_open_near_click = false
panel_placement = "floating"

[plugins]
enabled = [
    "yuuto/arch-updater",
    "noctalia/timer",
    "kenn/keybind-cheatsheet",
    "noctalia/screen_recorder",
    "yocraft/web-launcher",
    "oldirtty/color_picker",
    "radimous/prismlauncher-instances"
]

[shell]
app_icon_color = "primary"
corner_radius_scale = 2.0
font_family = "Adwaita Sans"
niri_overview_type_to_launch_enabled = true
panel_anchor_bar = "default"
password_style = "random"
popup_shadows = false
screen_time_enabled = true
settings_show_advanced = false
show_location = false

    [shell.animation]
    speed = 2.0000000298023224

    [shell.launcher]
    categories = false

        [shell.launcher.dmenu.entry.keybinds]
        command = "printf 'Open	Show keybind cheatsheet'"
        exec = "noctalia msg panel-open kenn/keybind-cheatsheet:cheatsheet"
        global = false
        glyph = "keyboard"
        label = "Keybind Cheatsheet"
        prefix = "keys"

        [shell.launcher.dmenu.entry.screen_recorder]
        command = """printf 'Start/Stop Recording	Start or stop recording
Save Replay	Save replay buffer to file
Start/Stop Replay Buffer	Start/stop replay buffer
'"""
        exec = "case \"{selection}\" in \"Start/Stop Recording\"*) noctalia msg plugin noctalia/screen_recorder:service all toggle ;; \"Save Replay\"*) noctalia msg plugin noctalia/screen_recorder:service all replay-save ;; \"Start/Stop Replay Buffer\"*) noctalia msg plugin noctalia/screen_recorder:service all replay-toggle ;; esac"
        global = false
        glyph = "video"
        label = "Screen Recorder"
        prefix = "rec"

        [shell.launcher.dmenu.entry.warp]
        command = """printf 'Connect	Connect to WARP
Disconnect	Disconnect from WARP
Status	Show connection status
'"""
        exec = "case \"{selection}\" in \"Connect\"*) warp-cli connect && sleep 1 && notify-send 'WARP' \"$(warp-cli status)\" || notify-send 'WARP' 'Failed to connect' ;; \"Disconnect\"*) warp-cli disconnect && sleep 1 && notify-send 'WARP' \"$(warp-cli status)\" || notify-send 'WARP' 'Failed to disconnect' ;; \"Status\"*) notify-send 'WARP Status' \"$(warp-cli status)\" ;; esac"
        global = false
        glyph = "shield"
        label = "Cloudflare WARP"
        prefix = "warp"

        [shell.launcher.providers.calculator]
        global = true

    [shell.panel]
    control_center_placement = "floating"
    control_center_position = "center"
    list_item_background = true
    wallpaper_placement = "floating"
    wallpaper_position = "center"

    [shell.screenshot]
    confirm_region = true
    directory = "/home/hihity/Pictures/Screenshots"
    filename_pattern = "screen-%H:%M_%d.%m"
    remember_last_region = true

    [shell.shadow]
    direction = "down_left"

[theme]
builtin = "Noctalia"
community_palette = "Oxocarbon"
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "gtk3", "gtk4", "hyprland", "kitty", "niri", "qt" ]
    community_ids = [
        "pywalfox",
        "discord",
        "telegram",
        "driftwm",
        "neovim",
        "obsidian",
        "prismlauncher",
        "steam",
        "papirus-icons",
        "bat",
        "lazygit",
        "yazi"
    ]

[wallpaper]
fill_color = "on_secondary"
transition = [ "fade" ]

    [wallpaper.automation]
    recursive = false

    [wallpaper.default]
    path = "/home/hihity/Pictures/Wallpapers/i-01.png"

    [wallpaper.last]
    path = "/home/hihity/Pictures/Wallpapers/i-01.png"

    [wallpaper.monitors.DVI-D-1]
    path = "/home/hihity/Pictures/Wallpapers/i-01.png"

[weather]
enabled = false

[widget.battery]
enabled = false

[widget.tray]
drawer = true
drawer_item_size = 20.0
match_adjacent_spacing = true

[widget.widget]
type = "yuuto/arch-updater:widget"

[widget.workspaces]
focused_output_only = true
style = "minimal"