config_version = 12

[backdrop]
enabled = true

[bar]
order = [ "default" ]

    [bar.default]
    background_opacity = 0.89999997988343239
    border = "primary"
    capsule_radius = 12
    capsule_thickness = 0.79999998584389687
    color = "primary"
    end = [ "bluetooth", "volume", "keyboard_layout", "notifications", "tray", "session" ]
    font_weight = 700
    margin_edge = 8
    margin_ends = 8
    panel_overlap = 0
    scale = 1.1500000096857548
    shadow = false
    start = [ "text_2", "workspaces", "sysmon" ]
    thickness = 32
    widget_spacing = 8

        [bar.default.dead_zone.actions]
        right = "none"

[control_center]
hidden_tabs = [ "monitor", "power", "bluetooth" ]

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "clipboard"

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
background_opacity = 0.89999997988343239
icon_size = 32
layer = "overlay"
position = "right"
radius = 12
shadow = false

[hooks]
colors_changed = "killall xdg-desktop-portal-gtk xdg-desktop-portal"
theme_mode_changed = "killall xdg-desktop-portal-gtk xdg-desktop-portal"
wallpaper_changed = "killall xdg-desktop-portal-gtk xdg-desktop-portal"

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 300.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 600.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 600.0

[location]
address = "Belarus,Akhrëmovtsy"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@DVI-D-1", "lockscreen-widget-0000000000000007" ]

    [lockscreen_widgets.grid]
    cell_size = 8
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DVI-D-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 640.0
    cy = 718.0
    output = "DVI-D-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DVI-D-1".settings]
        background_color = "surface"
        background_opacity = 0.90000000000000002
        background_radius = 12.0
        center_password_text = true
        input_opacity = 0.90000000000000002
        input_radius = 12.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = false
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000007]
    box_height = 144.0
    box_width = 384.0
    cx = 656.0
    cy = 548.0
    output = "DVI-D-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000007.settings]
        background_opacity = 0.90000000000000002
        background_radius = 12
        color = "primary"
        shadow = false

[nightlight]
temperature_day = 7400
temperature_night = 5700

[notification]
background_opacity = 0.89999997988343239
layer = "overlay"
show_actions = false

[osd]
background_opacity = 0.89999997988343239
offset_y = 14
position = "bottom_center"
position_vertical = "bottom_center"

    [osd.kinds]
    bluetooth = false
    brightness = false
    keyboard_backlight = false
    keyboard_layout = false
    lock_keys = false
    nightlight = false
    power_profile = false
    privacy = false
    wifi = false

[plugin_settings."noctalia/screen_recorder"]
directory = "/home/hihity/media/videos/recordings"
filename_pattern = "record-%H:%M_%d.%m"
replay_duration = 15
replay_enabled = true
replay_filename_pattern = "replay-%H:%M_%d.%m"
show_cursor = false
video_source = "focused"

[plugin_settings."noctalia/timer"]
panel_open_near_click = false
panel_placement = "floating"

[plugin_settings."nomadcxx/gslapper"]
glyph = ""
picker_placement = "floating"
scale = "stretch"

[plugin_settings."radimous/prismlauncher-instances"]
launcher_exec_command = "elyprismlauncher"
prism_path = "~/.local/share/ElyPrismLauncher"

[plugin_settings."whyoolw/dropwall"]
layer = "bottom"
per_monitor = true

[plugin_settings."yocraft/web-launcher"]
icon_provider = "duckduckgo"
links = [
    "Soundcloud|https://soundcloud.com/",
    "YouTube|https://youtube.com",
    "Reddit|https://reddit.com",
    "Mail|https://mail.proton.me",
    "GitHub|https://github.com"
]

[plugin_settings."yuuto/arch-updater"]
aur_helper = "paru"
flatpak_enabled = false
panel_open_near_click = false
panel_placement = "floating"

[plugins]
enabled = [
    "yuuto/arch-updater",
    "noctalia/timer",
    "kenn/keybind-cheatsheet",
    "noctalia/screen_recorder",
    "yocraft/web-launcher",
    "oldirtty/color_picker",
    "radimous/prismlauncher-instances",
    "noctalia/translator",
    "whyoolw/dropwall",
    "alexander/game-launcher"
]

[shell]
app_icon_color = "primary"
corner_radius_scale = 2.0
font_family = "Adwaita Sans"
niri_overview_type_to_launch_enabled = true
panel_anchor_bar = "default"
password_style = "random"
polkit_agent = true
popup_shadows = false
screen_time_enabled = true
show_location = false

    [shell.greeter_sync]
    auto_sync = true

    [shell.launcher]
    categories = false

        [shell.launcher.dmenu.entry.keybinds]
        command = "printf 'Open	Show keybind cheatsheet'"
        exec = "noctalia msg panel-open kenn/keybind-cheatsheet:cheatsheet"
        global = false
        glyph = "keyboard"
        label = "Keybind Cheatsheet"
        prefix = "keys"

        [shell.launcher.dmenu.entry.screen_recorder]
        command = """printf 'Start/Stop Recording	Start or stop recording
Save Replay	Save replay buffer to file
Start/Stop Replay Buffer	Start/stop replay buffer
'"""
        exec = "case \"{selection}\" in \"Start/Stop Recording\"*) noctalia msg plugin noctalia/screen_recorder:service all toggle ;; \"Save Replay\"*) noctalia msg plugin noctalia/screen_recorder:service all replay-save ;; \"Start/Stop Replay Buffer\"*) noctalia msg plugin noctalia/screen_recorder:service all replay-toggle ;; esac"
        global = false
        glyph = "video"
        label = "Screen Recorder"
        prefix = "rec"

        [shell.launcher.dmenu.entry.warp]
        command = """printf 'Connect	Connect to WARP
Disconnect	Disconnect from WARP
Status	Show connection status
'"""
        exec = "case \"{selection}\" in \"Connect\"*) warp-cli connect && sleep 1 && notify-send 'WARP' \"$(warp-cli status)\" || notify-send 'WARP' 'Failed to connect' ;; \"Disconnect\"*) warp-cli disconnect && sleep 1 && notify-send 'WARP' \"$(warp-cli status)\" || notify-send 'WARP' 'Failed to disconnect' ;; \"Status\"*) notify-send 'WARP Status' \"$(warp-cli status)\" ;; esac"
        global = false
        glyph = "shield"
        label = "Cloudflare WARP"
        prefix = "warp"

    [shell.panel]
    clipboard_placement = "attached"
    control_center_position = "center"
    launcher_placement = "attached"
    list_item_background = true
    open_near_click_clipboard = true
    open_near_click_control_center = true
    open_near_click_launcher = true
    open_near_click_session = true
    open_near_click_wallpaper = true
    polkit_placement = "attached"
    shadow = false
    wallpaper_position = "center"

    [shell.screenshot]
    confirm_region = true
    directory = "/home/hihity/media/pictures/screenshots"
    filename_pattern = "screen-%H:%M_%d.%m"
    remember_last_region = true

    [shell.shadow]
    direction = "down_left"

[theme]
builtin = "Noctalia"
community_palette = "ADW"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "gtk3", "gtk4", "hyprland", "kitty", "niri", "qt", "starship" ]
    community_ids = [
        "pywalfox",
        "pywalfox-beta4",
        "discord",
        "telegram",
        "driftwm",
        "micro",
        "neovim",
        "obsidian",
        "zed",
        "prismlauncher",
        "steam",
        "fastfetch",
        "papirus-icons",
        "bat",
        "fzf",
        "lazygit",
        "yazi"
    ]

[wallpaper]
directory = "/home/hihity/media/pictures/wallpapers"
transition = [ "fade" ]

    [wallpaper.automation]
    recursive = false

    [wallpaper.default]
    path = "/home/hihity/media/pictures/wallpapers/anime/a-05.png"

    [wallpaper.last]
    path = "/home/hihity/media/pictures/wallpapers/anime/a-05.png"

    [wallpaper.monitors.DVI-D-1]
    path = "/home/hihity/media/pictures/wallpapers/anime/a-05.png"

[widget.audio_visualizer]
scale = 2.5
scroll_repeat = "steps"

[widget.battery]
enabled = false

[widget.clock]
capsule = true
capsule_padding = 2
capsule_radius = 14
scroll_repeat = "steps"

[widget.session]
capsule = true
capsule_border = "error"
capsule_fill = "error"
capsule_foreground = "error"
capsule_radius = 12
color = "surface"
font_family = "Adwaita Sans"
font_weight = 1000

[widget.sysmon]
custom_image_colorize = true
stat = "ram_used"

[widget.text_2]
capsule = true
capsule_border = "primary"
capsule_fill = "primary"
capsule_radius = 12
color = "surface"
icon_color = "tertiary"
text = "󰣇"
type = "text"

    [widget.text_2.actions]
    left = "panel-toggle clipboard"
    right = "panel-toggle control-center screen-time"

[widget.tray]
drawer = true
drawer_columns = 5
drawer_item_size = 20.0
match_adjacent_spacing = true

[widget.widget]
type = "yuuto/arch-updater:widget"

[widget.workspaces]
capsule = true
empty_color = "outline"
focused_output_only = true
style = "minimal"