[mgr]
ratio          = [1, 2, 4]
sort_by        = "natural"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
show_hidden    = false
show_symlink   = true
linemode       = "size"

[opener]
edit = [
  { run = 'nvim "$@"', block = true, desc = "Neovim" },
]
image = [
  { run = 'eog "$@"', orphan = true, desc = "Eye of GNOME" },
]
video = [
  { run = 'celluloid "$@"', orphan = true, desc = "Celluloid" },
]
audio = [
  { run = 'lollypop -f "$@"', orphan = true, desc = "Lollypop" },
  { run = 'celluloid "$@"', orphan = true, desc = "Celluloid" },
]
pdf = [
  { run = 'evince "$@"', orphan = true, desc = "Evince" },
]
open = [
  { run = 'xdg-open "$@"', orphan = true, desc = "Open (xdg)" },
]
extract = [
  { run = 'ya pub extract --list "$@"', desc = "Extract here" },
]

[open]
rules = [
  { mime = "image/*",          use = "image" },
  { mime = "video/*",          use = "video" },
  { mime = "audio/*",          use = "audio" },
  { mime = "application/pdf",  use = "pdf" },
  { mime = "application/zip",             use = "extract" },
  { mime = "application/x-tar",           use = "extract" },
  { mime = "application/x-7z-compressed", use = "extract" },
  { mime = "application/x-rar",           use = "extract" },
  { url  = "*",                use = "edit" },
]

[tasks]
micro_workers    = 10
macro_workers    = 25
bizarre_retry    = 5
image_alloc      = 536870912
image_bound      = [0, 0]
suppress_preload = false

[plugin]
preloaders = [
  { mime = "image/*", run = "noop" },
]

[input]
cursor_blink = false

[log]
enabled = false
