# Noctalia theme for snappy-switcher

[colors]
background = {{ colors.surface.default.hex }}aa
card_bg = {{ colors.surface_container.default.hex }}aa
card_selected =  {{ colors.surface_container_highest.default.hex }}ff
text_color = {{ colors.on_primary_container.default.hex }}dd
subtext_color =  {{ colors.on_primary_container.default.hex }}cc
border_color =  {{ colors.outline.default.hex }}ff
bundle_bg = {{ colors.secondary_container.default.hex}}ff
badge_bg =  {{ colors.secondary.default.hex }}aa
badge_text_color = {{ colors.on_secondary.default.hex }}aa
badge_bg_selected = {{ colors.secondary.default.hex }}cc
badge_text_color_selected = {{ colors.on_secondary.default.hex }}ff