gui:
  theme:
    activeBorderColor:
      - "#ffc49f"
      - bold
    inactiveBorderColor:
      - "#dfc0ae"
    searchingActiveBorderColor:
      - "#d6d497"
      - bold
    optionsTextColor:
      - "#d5c3b9"
    selectedLineBgColor:
      - "#d5c3b9"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#d5c3b9"
    cherryPickedCommitBgColor:
      - "#d6d497"
    markedBaseCommitFgColor:
      - "#d6d497"
    markedBaseCommitBgColor:
      - "#ffb4ab"
    unstagedChangesColor:
      - "#ffb4ab"
    defaultFgColor:
      - "#ebe0dc"
