gui:
  theme:
    activeBorderColor:
      - "#ebc2d6"
      - bold
    inactiveBorderColor:
      - "#d6c1ca"
    searchingActiveBorderColor:
      - "#f5c2b0"
      - bold
    optionsTextColor:
      - "#d1c3c8"
    selectedLineBgColor:
      - "#d1c3c8"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#d1c3c8"
    cherryPickedCommitBgColor:
      - "#f5c2b0"
    markedBaseCommitFgColor:
      - "#f5c2b0"
    markedBaseCommitBgColor:
      - "#ffb4ab"
    unstagedChangesColor:
      - "#ffb4ab"
    defaultFgColor:
      - "#e8e1e2"
