--color=bg:#151314
--color=bg+:#ebc2d6
--color=fg:#e8e1e2
--color=fg+:#151314
--color=hl:#ebc2d6
--color=hl+:#151314
--color=info:#d6c1ca
--color=marker:#f5c2b0
--color=prompt:#ebc2d6
--color=spinner:#f5c2b0
--color=pointer:#f5c2b0
--color=header:#d6c1ca
--color=border:#ebc2d6
--color=gutter:#151314
--color=preview-bg:#221f20
