--color=bg:#171210
--color=bg+:#ffc49f
--color=fg:#ebe0dc
--color=fg+:#171210
--color=hl:#ffc49f
--color=hl+:#171210
--color=info:#dfc0ae
--color=marker:#d6d497
--color=prompt:#ffc49f
--color=spinner:#d6d497
--color=pointer:#d6d497
--color=header:#dfc0ae
--color=border:#ffc49f
--color=gutter:#171210
--color=preview-bg:#231f1c
