# Noctalia theme for fzf (fish)
# Generated by Noctalia community-templates — do not edit by hand.

set -gx FZF_DEFAULT_OPTS "\
  --color=bg+:#353436 \
  --color=bg:#131315 \
  --color=fg:#e5e1e3 \
  --color=fg+:#e5e1e3 \
  --color=hl:#c4c5dc \
  --color=hl+:#c4c5dc \
  --color=info:#c7c5d0 \
  --color=marker:#dcbed0 \
  --color=prompt:#c4c5dc \
  --color=spinner:#dcbed0 \
  --color=pointer:#c4c5dc \
  --color=header:#c7c5cd \
  --color=border:#919097 \
  --color=gutter:#131315 \
  --color=preview-bg:#201f21"
