--color=bg:{{colors.background.default.hex}}
--color=bg+:{{colors.primary.default.hex}}
--color=fg:{{colors.on_background.default.hex}}
--color=fg+:{{colors.background.default.hex}}
--color=hl:{{colors.primary.default.hex}}
--color=hl+:{{colors.background.default.hex}}
--color=info:{{colors.secondary.default.hex}}
--color=marker:{{colors.tertiary.default.hex}}
--color=prompt:{{colors.primary.default.hex}}
--color=spinner:{{colors.tertiary.default.hex}}
--color=pointer:{{colors.tertiary.default.hex}}
--color=header:{{colors.secondary.default.hex}}
--color=border:{{colors.primary.default.hex}}
--color=gutter:{{colors.background.default.hex}}
--color=preview-bg:{{colors.surface_container.default.hex}}
