color0 #51443d
color1 #ffb4ab
color2 #ffc49f
color3 #dfc0ae
color4 #d6d497
color5 #f4ba95
color6 #dfc0ae
color7 #ebe0dc
color8 #9e8e85
color9 #ffb4ab
color10 #ffc49f
color11 #dfc0ae
color12 #d6d497
color13 #f4ba95
color14 #dfc0ae
color15 #ebe0dc

cursor                #ebe0dc
cursor_text_color     #171210
background            #171210
foreground            #ebe0dc
selection_foreground  #d5c3b9
selection_background  #51443d
active_border_color   #ffc49f
inactive_border_color #51443d
url_color             #ffc49f

active_tab_foreground   #4b270d
active_tab_background   #ffc49f
inactive_tab_foreground #d5c3b9
inactive_tab_background #51443d
cursor_trail_color      #d5c3b9
