color0 #50443c
color1 #ffb4ab
color2 #f2bb91
color3 #dec1ac
color4 #caca8f
color5 #f2bb91
color6 #dec1ac
color7 #eae1db
color8 #9d8e84
color9 #ffb4ab
color10 #f2bb91
color11 #dec1ac
color12 #caca8f
color13 #f2bb91
color14 #dec1ac
color15 #eae1db

cursor                #eae1db
cursor_text_color     #171310
background            #171310
foreground            #eae1db
selection_foreground  #d5c3b8
selection_background  #50443c
active_border_color   #f2bb91
inactive_border_color #50443c
url_color             #f2bb91

active_tab_foreground   #492809
active_tab_background   #f2bb91
inactive_tab_foreground #d5c3b8
inactive_tab_background #50443c
cursor_trail_color      #d5c3b8
