color0 #141317
color1 #ffb4ab
color2 #c6bfff
color3 #c8c3e2
color4 #fab0e1
color5 #c6bfff
color6 #c8c3e2
color7 #e5e1e7
color8 #928f9b
color9 #ffb4ab
color10 #c6bfff
color11 #c8c3e2
color12 #fab0e1
color13 #c6bfff
color14 #c8c3e2
color15 #e5e1e7

cursor                #e5e1e7
cursor_text_color     #141317
background            #141317
foreground            #e5e1e7
selection_foreground  #c8c5d1
selection_background  #474550
active_border_color   #c6bfff
inactive_border_color #474550
url_color             #c6bfff

active_tab_foreground   #2e2864
active_tab_background   #c6bfff
inactive_tab_foreground #c8c5d1
inactive_tab_background #474550
cursor_trail_color      #c8c5d1
